# Generated by Django 5.2 on 2025-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_voting_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
