# Generated by Django 5.2 on 2025-05-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_is_voting_candidate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookvote',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='bookvote',
            index=models.Index(fields=['user', 'book', 'voted_at'], name='vote_unique_idx'),
        ),
        migrations.AlterModelTable(
            name='bookvote',
            table='core_bookvote',
        ),
    ]
