# Generated by Django 5.2 on 2025-05-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_votingperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreview',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='meetingreview',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='meetingreview',
            name='question3',
        ),
        migrations.CreateModel(
            name='MeetingReviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_questions', to='core.meeting')),
                ('question1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_question1', to='core.reviewquestion')),
                ('question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_question2', to='core.reviewquestion')),
                ('question3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_question3', to='core.reviewquestion')),
            ],
            options={
                'unique_together': {('meeting',)},
            },
        ),
    ]
