# Generated by Django 5.2 on 2025-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_meetingreview_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
