# Generated by Django 5.2 on 2025-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_meeting_max_attendees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='meetingreviewquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterUniqueTogether(
            name='bookvote',
            unique_together={('user', 'book')},
        ),
    ]
