# Generated by Django 5.2 on 2025-06-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookvote',
            name='vote_unique_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bookvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookvote',
            name='voting_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.votingperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='bookvote',
            unique_together={('user', 'book', 'voting_period')},
        ),
        migrations.AddIndex(
            model_name='bookvote',
            index=models.Index(fields=['user', 'book', 'voting_period', 'voted_at'], name='vote_unique_idx'),
        ),
    ]
