# Generated by Django 5.2 on 2025-06-09 21:45

from django.db import migrations
import django.db.models  # Импорт модуля models

def populate_voting_period(apps, schema_editor):
    VotingPeriod = apps.get_model('core', 'VotingPeriod')
    BookVote = apps.get_model('core', 'BookVote')
    for vote in BookVote.objects.all():
        active_period = VotingPeriod.objects.filter(
            start_date__lte=vote.voted_at,
            end_date__gte=vote.voted_at
        ).order_by('-start_date').first()
        if active_period:
            vote.voting_period = active_period
            vote.save(update_fields=['voting_period'])
        else:
            # Логика для случаев, если период не найден
            print(f"No matching VotingPeriod found for vote {vote.id} at {vote.voted_at}")

def reverse_populate_voting_period(apps, schema_editor):
    # Обратная операция (опционально, для отката)
    BookVote = apps.get_model('core', 'BookVote')
    BookVote.objects.update(voting_period=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_bookvote_vote_unique_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_voting_period, reverse_code=reverse_populate_voting_period),
        migrations.AlterField(
            model_name='bookvote',
            name='voting_period',
            field=django.db.models.ForeignKey(on_delete=django.db.models.CASCADE, related_name='votes', to='core.votingperiod'),
        ),
    ]