# Generated by Django 5.2 on 2026-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_bookvote_voting_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(blank=True, default='default', max_length=50, verbose_name='Иконка аватара'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
