# Generated by Django 5.2 on 2026-01-17 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_avatar_icon_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(blank=True, default='default', max_length=50, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='Role of user'),
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Type of action')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='Object')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID of object')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Log of admin',
                'verbose_name_plural': 'Logs of admins',
                'ordering': ['-timestamp'],
            },
        ),
    ]
