# Generated by Django 5.2 on 2026-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_avatar_icon_alter_user_role_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Помечает пользователя как удалённого без потери данных', verbose_name='Soft-deleted (удалён)'),
        ),
    ]
