# Generated by Django 5.2 on 2026-01-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Если пользователь забанен, он не может авторизоваться', verbose_name='Заблокирован (бан)'),
        ),
    ]
