# Generated by Django 5.2 on 2026-03-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_user_is_deleted_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='discussed_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.book'),
        ),
    ]
