# Generated by Django 5.2 on 2026-03-26 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_meeting_discussed_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingregistration',
            name='attendance_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingregistration',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingregistration',
            name='is_attended',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
