# Generated by Django 5.2 on 2026-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_meetingregistration_attendance_marked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('BOOK_DISCUSSION', 'Book Discussion'), ('LECTURE_DISCUSSION', 'Lecture and Discussion'), ('WORKSHOP', 'Workshop'), ('MOVIE_SCREENING', 'Movie Screening')], default='BOOK_DISCUSSION', max_length=20),
        ),
    ]
