# Generated by Django 5.2 on 2026-03-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_book_is_archived_votingperiod_max_votes_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingperiod',
            name='max_votes_per_user',
        ),
    ]
