# Generated by Django 5.2 on 2026-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_votingperiod_max_votes_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(choices=[('default', 'Default'), ('book', 'Book'), ('star', 'Star'), ('owl', 'Owl'), ('cat', 'Cat'), ('coffee', 'Coffee')], default='default', max_length=50, verbose_name='Avatar'),
        ),
    ]
