# Generated by Django 5.2 on 2026-04-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_user_avatar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to='core.meetingregistration', verbose_name='Related registration'),
        ),
    ]
