# Generated by Django 5.2 on 2026-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingperiod',
            name='voting_mode',
            field=models.CharField(choices=[('open', 'Открытое голосование'), ('closed', 'Закрытое голосование')], default='closed', max_length=20, verbose_name='Режим голосования'),
        ),
    ]
