"""
Django settings for bookclub project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uap=1!gc6-sy=&!dt*)dxuo-_f@^(1@+f+u7a$jzl)lr(bi4be'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # Твоё приложение
    'rest_framework',#Фреймворк для перевода из JSON в PY(DRF)
    'corsheaders', #Настройка портов у Джанго и Реакта
    'rest_framework_simplejwt',  # Для JWT-аутентификации
    'django_filters',  # Для фильтрации в API
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',#Защищает от уязвимостей (например, HTTPS).
    'django.contrib.sessions.middleware.SessionMiddleware',#Поддерживает сессии (например, для админки).
    'corsheaders.middleware.CorsMiddleware',  # Добавить для CORS
    'django.middleware.common.CommonMiddleware',#Обрабатывает общие заголовки и редиректы.
    'django.middleware.csrf.CsrfViewMiddleware',#Защищает от CSRF-атак (для POST-запросов).
    'django.contrib.auth.middleware.AuthenticationMiddleware',#Поддерживает аутентификацию пользователей.
    'django.contrib.messages.middleware.MessageMiddleware',#Для сообщений (например, в админке).
    'django.middleware.clickjacking.XFrameOptionsMiddleware',#Защищает от кликджекинга.
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Только авторизованные пользователи
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30), #Access-токен действует 20 минут. (сейчас час, потом - сменить!)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), #Refresh-токен действует 1 день.
    'ROTATE_REFRESH_TOKENS': False,#Настройка времени жизни токена
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
}

ROOT_URLCONF = 'bookclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookclub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bookclub_db',
        'USER': 'postgres',  # Замени на твоего пользователя PostgreSQL
        'PASSWORD': 'postgres',  # Замени на твой пароль
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

# Use Chelyabinsk timezone (UTC+5) across the project
TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Изменяем на абсолютный путь, чтобы не путаться
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Директория для хранения статических файлов (например, images/)
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
SESSION_ENGINE = 'django.contrib.sessions.backends.db'